/**
 * Seed script to populate the blogPosts collection in Firestore.
 * Run with: npx ts-node --project tsconfig.json scripts/seed-blog.ts
 * Or simply visit /api/seed-blog in the browser (dev only).
 */

export const BLOG_POSTS = [
  {
    slug: 'descripcion-puesto-efectiva',
    title: "Cómo Escribir una Descripción de Puesto que Atraiga Talento",
    excerpt: "Tu descripción de puesto es tu primer argumento de venta. Aprende a redactar vacantes que atraigan candidatos calificados, incluyan el rango salarial correcto y reflejen tu cultura real.",
    category: "Guías para Empresas",
    date: "2024-12-15",
    published: true,
    content: [
      "Cada vacante publicada es una oportunidad para comunicar no solo lo que necesitas, sino quién eres como empresa. Una descripción de puesto bien redactada puede ser la diferencia entre recibir cientos de aplicaciones genéricas o atraer a los tres candidatos perfectos para tu equipo. En un mercado laboral cada vez más competitivo, donde el talento tiene opciones, tu descripción de puesto es tu primer argumento de venta.",
      "En Trabajo Libre hemos analizado miles de publicaciones de empleo y hemos identificado patrones claros: las vacantes que siguen estas prácticas reciben en promedio 3 veces más aplicaciones calificadas. Aquí te compartimos todo lo que necesitas saber.",
      "**1. Define el Perfil Ideal Antes de Escribir una Sola Palabra**",
      "El error más común es sentarse a redactar sin haber definido claramente qué necesitas. Antes de abrir tu editor, reúnete con el equipo que trabajará con esta persona y responde estas preguntas: ¿Qué problema resuelve este rol? ¿Qué habilidades son indispensables vs. deseables? ¿Qué tipo de personalidad encaja con la cultura del equipo? ¿Cuál es la trayectoria de crecimiento para esta posición? Esta claridad interna se traduce en una descripción externa precisa que atrae exactamente al perfil que buscas.",
      "**2. El Título del Puesto: Tu Primera Impresión**",
      "El título es lo primero que ven los candidatos al buscar empleo. Evita títulos internos que nadie buscaría (como \"Ninja de Ventas\" o \"Rockstar del Marketing\"). Usa títulos estándar de la industria que los candidatos realmente escriben en los buscadores. Por ejemplo, \"Gerente de Marketing Digital\" funciona mejor que \"Líder de Crecimiento Orgánico\". Si tienes un título creativo, inclúyelo entre paréntesis después del estándar.",
      "**3. Sé Específico con las Responsabilidades**",
      "Nada aleja más a un buen candidato que una lista genérica como \"será responsable de diversas tareas del área\". Detalla las 5-7 responsabilidades principales del rol, ordenadas por importancia. Usa verbos de acción: \"Diseñarás la estrategia de contenido para redes sociales\" es mucho más poderoso que \"Responsable de redes sociales\". Incluye el porcentaje aproximado de tiempo dedicado a cada área para que el candidato visualice su día a día.",
      "**4. Incluye el Rango Salarial — Sí, de Verdad**",
      "Sabemos que puede ser incómodo, pero los datos no mienten: las publicaciones con rango salarial reciben hasta 30% más aplicaciones y el proceso de contratación se reduce en un 40%. ¿Por qué? Porque eliminas de entrada a candidatos con expectativas fuera de tu rango, ahorrando tiempo a ambas partes. Si no puedes publicar un número exacto, al menos indica un rango como \"$25,000 - $35,000 MXN mensuales según experiencia\". La transparencia genera confianza desde el primer contacto.",
      "**5. Destaca la Cultura y los Beneficios Reales**",
      "Los candidatos de hoy no solo buscan un salario — buscan un lugar donde quieran estar. Menciona beneficios concretos: ¿Ofrecen horario flexible? ¿Días de home office? ¿Seguro de gastos médicos mayores? ¿Presupuesto para capacitación? Evita frases vacías como \"ambiente dinámico\" o \"empresa líder en su ramo\". En su lugar, di cosas como \"Los viernes salimos a las 3 PM\" o \"Cada empleado tiene $15,000 MXN anuales para cursos y conferencias\". Lo específico vende, lo genérico aburre.",
      "**6. Separa los Requisitos Indispensables de los Deseables**",
      "Un error frecuente es listar 15 requisitos como si todos fueran obligatorios. Esto desanima a muchos candidatos calificados, especialmente mujeres y minorías, que tienden a no aplicar si no cumplen el 100% de los requisitos. Divide claramente entre \"Requisitos indispensables\" (3-5 máximo) y \"Es un plus si tienes\" (los nice-to-have). Esto amplía tu pool de candidatos sin sacrificar calidad.",
      "**7. Optimiza para Búsqueda y Cierra con un Llamado a la Acción**",
      "Usa palabras clave que los candidatos realmente buscan. Si necesitas un \"Desarrollador Full Stack con React\", asegúrate de que esas palabras aparezcan de forma natural en el texto. Finalmente, cierra tu descripción con un llamado a la acción claro y cálido: \"Si te entusiasma este reto y quieres ser parte de un equipo que está cambiando la industria, nos encantaría conocerte. Aplica hoy y cuéntanos tu historia.\" Un toque humano al final puede ser lo que convierta a un lector curioso en un aplicante motivado.",
      "**Conclusión**",
      "Escribir una buena descripción de puesto no es solo un trámite administrativo — es una habilidad estratégica que impacta directamente la calidad de tu equipo. Invierte 30 minutos extra en pulir tu próxima vacante y verás la diferencia en la calidad de aplicaciones que recibes. En Trabajo Libre, te facilitamos publicar tu vacante de forma rápida y llegar a miles de profesionales calificados en toda Latinoamérica.",
    ],
  },
  {
    slug: 'habilidades-demandadas-2025',
    title: "10 Habilidades Más Demandadas en el Mercado Laboral 2025",
    excerpt: "Desde análisis de datos e IA hasta inteligencia emocional — analizamos miles de vacantes para identificar las 10 habilidades que más valoran los empleadores y cómo desarrollarlas.",
    category: "Desarrollo Profesional",
    date: "2024-12-10",
    published: true,
    content: [
      "El mercado laboral se ha transformado más en los últimos tres años que en la década anterior. La inteligencia artificial, el trabajo remoto y la digitalización acelerada han reconfigurado lo que las empresas buscan en sus colaboradores. Si estás buscando trabajo o quieres avanzar en tu carrera, conocer las habilidades más demandadas te dará una ventaja significativa frente a otros candidatos.",
      "Analizamos datos de miles de vacantes publicadas en Trabajo Libre y otras plataformas líderes para identificar las competencias que más valoran los empleadores en 2025. Aquí está nuestra lista, con consejos prácticos para desarrollar cada una.",
      "**1. Análisis de Datos**",
      "Ya no es una habilidad exclusiva de científicos de datos. Hoy, desde gerentes de marketing hasta directores de operaciones necesitan interpretar métricas, crear dashboards y tomar decisiones basadas en evidencia. No necesitas un doctorado en estadística: dominar Excel avanzado, Power BI o Google Analytics ya te posiciona por encima del 80% de los candidatos. Empieza con un curso gratuito de Google Data Analytics y practica con datos reales de tu trabajo o proyectos personales.",
      "**2. Inteligencia Artificial y Herramientas de IA**",
      "No se trata de saber programar modelos de machine learning (aunque ayuda). Lo que las empresas buscan es que sepas usar herramientas de IA para ser más productivo: desde ChatGPT y Copilot para redacción y código, hasta herramientas de automatización como Zapier o Make. Los profesionales que integran IA en su flujo de trabajo reportan un aumento del 40% en productividad. La clave está en saber hacer las preguntas correctas y evaluar críticamente las respuestas.",
      "**3. Gestión de Proyectos**",
      "Con equipos cada vez más distribuidos y proyectos más complejos, la capacidad de planificar, ejecutar y entregar resultados a tiempo es oro puro. Las metodologías ágiles (Scrum, Kanban) dominan en tecnología, pero se han expandido a marketing, recursos humanos y operaciones. Una certificación como PMP, Scrum Master o incluso un curso de Asana/Jira puede diferenciarte significativamente. Lo importante no es la herramienta, sino la mentalidad: dividir lo complejo en pasos manejables y mantener al equipo alineado.",
      "**4. Liderazgo y Comunicación Efectiva**",
      "No importa si eres junior o senior — la capacidad de comunicar ideas con claridad, dar y recibir retroalimentación, y influir sin autoridad formal es probablemente la habilidad más transferible que existe. En un mundo de trabajo remoto, comunicar bien por escrito es tan importante como hablar bien en una presentación. Practica escribiendo resúmenes ejecutivos, facilitando reuniones con agenda clara, y dando retroalimentación constructiva. Estas son las habilidades que te llevan de contribuidor individual a líder.",
      "**5. Marketing Digital**",
      "Toda empresa, sin importar su tamaño o industria, necesita presencia digital. El marketing digital abarca SEO, publicidad en redes sociales (Meta Ads, Google Ads), email marketing, content marketing y analítica web. La buena noticia es que es una de las habilidades más accesibles para aprender por tu cuenta: Google ofrece certificaciones gratuitas, Meta tiene Blueprint, y HubSpot tiene una academia completa. Si puedes demostrar que has generado resultados medibles (leads, ventas, tráfico), tendrás empleadores haciendo fila.",
      "**6. Ciberseguridad**",
      "Con el aumento exponencial de ataques cibernéticos en Latinoamérica (un 30% más que el año anterior), las empresas están desesperadas por profesionales que entiendan seguridad informática. No necesitas ser hacker ético para empezar: entender conceptos como phishing, gestión de contraseñas, protección de datos (LFPDPPP en México) y cumplimiento regulatorio ya te hace valioso. Las certificaciones CompTIA Security+ o CEH (Certified Ethical Hacker) son excelentes puertas de entrada a este campo con salarios muy competitivos.",
      "**7. Pensamiento Crítico y Resolución de Problemas**",
      "En una época donde la IA puede generar respuestas instantáneas, la capacidad humana de cuestionar supuestos, identificar sesgos y conectar información de diferentes fuentes se vuelve más valiosa que nunca. Las empresas buscan personas que no solo ejecuten tareas, sino que cuestionen si están resolviendo el problema correcto. Desarrolla esta habilidad leyendo contenido fuera de tu área, participando en debates y siempre preguntándote \"¿por qué?\" antes de aceptar algo como verdad.",
      "**8. Adaptabilidad y Aprendizaje Continuo**",
      "La tecnología que usas hoy probablemente será obsoleta en 3 años. Lo que las empresas realmente valoran no es que domines una herramienta específica, sino que puedas aprender rápidamente la siguiente. Demuestra adaptabilidad en tu CV mostrando cómo has cambiado de rol, aprendido nuevas tecnologías o asumido responsabilidades fuera de tu zona de confort. Los candidatos que dicen \"no sé, pero lo puedo aprender\" con evidencia de haberlo hecho antes son irresistibles para los reclutadores.",
      "**9. Colaboración Remota y Herramientas Digitales**",
      "Saber trabajar efectivamente sin estar en la misma oficina es ahora una competencia core, no un nice-to-have. Esto incluye dominar herramientas como Slack, Notion, Microsoft Teams, Zoom y Figma, pero también habilidades blandas como comunicación asíncrona, documentación proactiva y gestión autónoma del tiempo. Si puedes demostrar experiencia exitosa en equipos remotos o distribuidos, tienes una ventaja en el 60% de las vacantes publicadas actualmente.",
      "**10. Inteligencia Emocional**",
      "Quizás la habilidad más subestimada y a la vez más determinante para el éxito profesional a largo plazo. La inteligencia emocional — la capacidad de reconocer, entender y gestionar tus propias emociones y las de los demás — impacta directamente tu capacidad de negociar, liderar, resolver conflictos y construir relaciones profesionales duraderas. Los estudios muestran que el 90% de los profesionales de alto rendimiento tienen alta inteligencia emocional. No es algo con lo que naces: se desarrolla con práctica, autoconciencia y, a veces, con la ayuda de un buen mentor o coach.",
      "**¿Cómo Empezar?**",
      "No intentes desarrollar las 10 habilidades al mismo tiempo. Identifica 2-3 que sean más relevantes para tu carrera actual y enfócate en ellas durante los próximos 3 meses. Busca proyectos en tu trabajo actual donde puedas practicarlas, toma un curso en línea y busca un mentor que ya las domine. En Trabajo Libre, muchas vacantes especifican exactamente qué habilidades buscan — úsalas como guía para tu plan de desarrollo profesional.",
    ],
  },
  {
    slug: 'tendencias-laborales-2025',
    title: "Tendencias del Mercado Laboral 2025: Qué Esperar",
    excerpt: "Trabajo híbrido, IA en reclutamiento, transparencia salarial y la economía de habilidades. Un análisis completo de las 8 tendencias que están redefiniendo el mercado laboral en Latinoamérica.",
    category: "Tendencias",
    date: "2024-12-05",
    published: true,
    content: [
      "El mercado laboral latinoamericano está viviendo una transformación sin precedentes. Lo que hace cinco años era una tendencia emergente — trabajo remoto, automatización, contratación basada en habilidades — hoy es la norma en las empresas más competitivas de la región. Si eres candidato o empleador, entender estas tendencias no es opcional: es la diferencia entre liderar el cambio o quedarse atrás.",
      "En Trabajo Libre monitoreamos constantemente el comportamiento del mercado a través de los datos de nuestra plataforma. Aquí te compartimos las 8 tendencias más importantes que están definiendo el mundo laboral en 2025.",
      "**1. El Trabajo Híbrido se Consolida como el Nuevo Estándar**",
      "La discusión ya no es \"¿trabajo remoto sí o no?\" sino \"¿cuántos días en oficina?\". Los datos son contundentes: el 73% de los profesionales en Latinoamérica prefieren un modelo híbrido (2-3 días en oficina), y las empresas que ofrecen esta flexibilidad atraen candidatos un 40% más rápido que las que exigen presencialidad total. Sin embargo, el híbrido trae sus propios desafíos: empresas inteligentes están rediseñando sus oficinas como espacios de colaboración (no de escritorios individuales) y están invirtiendo en herramientas que faciliten la comunicación asíncrona. Si eres empleador, el mensaje es claro: la flexibilidad ya no es un beneficio, es una expectativa básica.",
      "**2. La Inteligencia Artificial Transforma los Recursos Humanos**",
      "La IA no va a reemplazar a los reclutadores, pero los reclutadores que usen IA van a reemplazar a los que no. En 2025, vemos empresas usando IA para: filtrar y rankear CVs automáticamente, generar descripciones de puesto optimizadas, realizar screening inicial de candidatos por chat, predecir qué candidatos tienen mayor probabilidad de éxito en el rol, e identificar riesgos de rotación en empleados actuales. Lo importante es usar estas herramientas para eliminar sesgos y acelerar procesos, no para deshumanizar la contratación. La decisión final siempre debe ser humana.",
      "**3. Bienestar Laboral: De Beneficio a Estrategia de Negocio**",
      "Las empresas que invierten en bienestar laboral no lo hacen por altruismo — lo hacen porque funciona. Los datos muestran que cada peso invertido en programas de bienestar genera un retorno de $4 en productividad y reducción de ausentismo. En 2025, las iniciativas más impactantes incluyen: acceso a terapia psicológica subsidiada, horarios flexibles para padres y cuidadores, semanas de 4 días (varias empresas mexicanas ya lo implementan), presupuesto para home office y ergonomía, y días de descanso por salud mental sin necesidad de justificación médica. Como candidato, no temas preguntar sobre estas políticas en tus entrevistas — las mejores empresas estarán orgullosas de responder.",
      "**4. La Economía de Habilidades Supera a la Economía de Títulos**",
      "Cada vez más empresas en Latinoamérica están eliminando el requisito de título universitario para posiciones donde la experiencia y las habilidades demostradas son más relevantes. Gigantes como Google, Apple e IBM lideraron esta tendencia, y ahora vemos empresas mexicanas, colombianas y brasileñas siguiendo el mismo camino. Lo que importa es qué sabes hacer, no dónde lo aprendiste. Las certificaciones de plataformas como Coursera, Google Career Certificates y bootcamps de programación están ganando el mismo peso que un título tradicional para muchos empleadores. Si eres candidato, invierte en construir un portafolio sólido que demuestre tus habilidades con resultados tangibles.",
      "**5. Diversidad e Inclusión: De Discurso a Métricas**",
      "La diversidad dejó de ser un tema de relaciones públicas para convertirse en una prioridad medible. Las empresas más avanzadas ya no solo hablan de diversidad — la miden con KPIs específicos: porcentaje de mujeres en liderazgo, brecha salarial por género, representación de grupos minoritarios, tasas de promoción equitativas por demografía. Los datos respaldan la inversión: equipos diversos toman mejores decisiones el 87% del tiempo y las empresas con mayor diversidad generan un 35% más de ingresos que sus competidores menos diversos. Si buscas empleo, investiga los programas de D&I de tus empresas objetivo — dice mucho sobre su cultura real.",
      "**6. Upskilling y Reskilling: La Capacitación Continua es Supervivencia**",
      "El World Economic Forum estima que el 44% de las habilidades actuales quedarán obsoletas en los próximos 5 años. Las empresas que entienden esto están invirtiendo fuertemente en capacitar a su talento actual en lugar de buscar reemplazos externos. Programas de upskilling (mejorar habilidades existentes) y reskilling (aprender habilidades completamente nuevas) se están convirtiendo en el beneficio más valorado después del salario. Si tu empresa no invierte en tu desarrollo, es una señal de alerta. Y si eres empleador, recuerda: es más barato capacitar a un buen empleado que reemplazarlo.",
      "**7. Transparencia Salarial: El Fin del \"Salario Competitivo\"**",
      "La frase \"salario competitivo\" sin números está muriendo — y con razón. Cada vez más países y estados están legislando la transparencia salarial, y las empresas que la adoptan voluntariamente reportan procesos de contratación más rápidos, mayor satisfacción de empleados y menor rotación. En Trabajo Libre, las vacantes que incluyen rango salarial reciben significativamente más aplicaciones que las que no lo hacen. La transparencia no solo atrae más candidatos — atrae mejores candidatos, porque elimina la incertidumbre y demuestra que valoras el tiempo de todos.",
      "**8. Contratación Digital: Rapidez y Alcance sin Precedentes**",
      "La forma en que las empresas contratan ha cambiado permanentemente. Los procesos de selección que antes tomaban 45-60 días ahora se completan en 2-3 semanas gracias a plataformas digitales, entrevistas por video y evaluaciones automatizadas. Plataformas como Trabajo Libre permiten a las empresas publicar una vacante y comenzar a recibir aplicaciones calificadas en cuestión de horas, no semanas. Para los candidatos, esto significa más oportunidades y procesos más ágiles. Para las empresas, significa acceso a un pool de talento que antes era inalcanzable.",
      "**Mirando Hacia Adelante**",
      "El mercado laboral de 2025 premia la adaptabilidad, la transparencia y la inversión en personas. Ya sea que estés buscando tu próximo empleo o contratando para tu equipo, las empresas y candidatos que abracen estas tendencias estarán mejor posicionados para prosperar. En Trabajo Libre, estamos comprometidos con hacer que la conexión entre talento y oportunidades sea más rápida, más justa y más accesible para toda Latinoamérica.",
    ],
  },
]
